gym finsweet pr
edson-pro/gym-finsweet pull request #1
Opened 2022-10-03 12:01 UTC by edson-pro

2022-10-03 14:59 UTC, mbukeRepo reviewed
Apply these changes and try to implement BEM.

2022-10-03 14:59 UTC, mbukeRepo commented on src/index.html
> +    <div class="more-info__background"></div>
`more-info__background` is an element of `more-info`. where is the `more-info` block.

2022-10-03 15:41 UTC, rithaven commented on src/index.html
> +      <div class="footer__background"></div>
Where is the block of this element? you should have "footer" block in order to use "footer__background" element

2022-10-03 16:05 UTC, ritha-kankindi approved these changes

2022-10-03 17:01 UTC, mbukeRepo approved these changes
LGTM

2022-10-12 07:45 UTC, rithaven commented on src/index.html
> +            <a class="button button--primary ml-5" href="">Free trial</a>
This Button is inside nav block. you should write "nav__button nav__button--primary" in order to help anyone who can view your codes to differentiate this button from other buttons you would have in our project.

2022-10-12 07:46 UTC, rithaven commented on src/index.html
> +            <a class="button button--primary" href="">Get Free trial</a>
Here also

2022-10-12 07:49 UTC, rithaven commented on src/index.html
> +      <div class="work-with-us">
a block inside another block it is not a good practice in BEM

2022-10-12 07:50 UTC, rithaven commented on src/index.html
> +            <img src="./img/ArrowIcon.svg" />
This image must have a class name

2022-10-12 07:51 UTC, rithaven commented on src/index.html
> +            <img src="./img/ArrowIcon.svg" />
Here also

2022-10-12 07:54 UTC, rithaven reviewed
It's a good practice to not mix BEM and tailwind within the same class name because it is a kinder confusing for someone who can view your codes.

2022-10-12 08:52 UTC, mbukeRepo requested changes
Please apply these changes :computer:

2022-10-12 08:52 UTC, mbukeRepo commented on src/index.html
> +      <div class="hero relative">
`relative` global modifiers are not allowed in BEM. `tailwind` classes are not allowed

2022-10-12 08:52 UTC, mbukeRepo commented on src/index.html
> +          <h4 class="section__title">
here also

2022-10-12 08:52 UTC, mbukeRepo commented on src/index.html
> +          <span class="section__tagline"> Why should you work with us? </span>
you started new block `work-with-us` and you are still using `section` block

2022-10-12 08:52 UTC, mbukeRepo commented on src/index.html
> +    <div class="section py-8" style="background: url(./img/Mask.png)">
tailwind classes are not allowed

2022-10-12 08:52 UTC, mbukeRepo commented on src/index.html
> +          <h4 class="section__title">More impressions, more conversions</h4>
why `section__title` when you are in `impressions` block

2022-10-12 08:52 UTC, mbukeRepo commented on src/index.html
> +          <p class="section__subtitle">
here also

2022-10-12 08:52 UTC, mbukeRepo commented on src/index.html
> +            <li class="">About Us</li>
empty class on `li` 's

2022-10-12 08:52 UTC, mbukeRepo commented on src/product.html
> +          <p class="font-[600] text-[18px] mb-[20px]">
tailwind classes are not allowed in the `html` file

2022-10-12 12:41 UTC, rithaven commented on src/index.html
> +      <div class="solutions_body">
Typo erro "_"

2022-10-12 12:44 UTC, rithaven commented on src/index.html
> +            class="solutions__cart-subtitletext-sm font-semibold text-gray-500"
Tailwind and BEM in the same class name it is not a good practice

2022-10-12 12:47 UTC, rithaven commented on src/input.css
> +  @apply flex rounded-md py-[5px] items-center px-4 bg-[#2B2E3C];
Change this py-[5px]

2022-10-12 12:48 UTC, ritha-kankindi commented on src/input.css
> +  @apply text-black  outline-none bg-transparent placeholder:text-[white] placeholder:opacity-[0.5] text-[16px] pl-[12px];
Here also

2022-10-12 12:49 UTC, rithaven commented on src/input.css
> +  @apply text-base font-semibold bg-clip-text text-transparent bg-gradient-to-r from-[#373FFF] to-[#3ACAF8] mb-[20px];
Here also

2022-10-12 12:49 UTC, rithaven commented on src/input.css
> +  @apply text-3xl font-bold leading-10 mb-[20px] text-[#1D2130];
Here also

2022-10-12 12:49 UTC, rithaven commented on src/input.css
> +  @apply h-11 w-11 mt-auto mb-auto flex items-center justify-center rounded-[50%] bg-[#F4F5F7];
Here also

2022-10-12 13:18 UTC, rithaven approved these changes

2022-10-12 13:31 UTC, mbukeRepo approved these changes
LGTM :thumbsup:

2022-10-12 17:34 UTC, musayann requested changes
Looks great, however, there are some small issues to address

2022-10-12 17:34 UTC, musayann commented on src/index.html
> +            <a class="button button--primary ml-5" href="">Free trial</a>
The class name is not consistent with the parent block

2022-10-12 17:34 UTC, musayann commented on src/index.html
> +    <div class="impresions" style="background: url(./img/Mask.png)">
Please move the style definition in the CSS file

2022-10-12 17:34 UTC, musayann commented on src/index.html
> +      <button class="button button--primary">Free trial</button>
The class name is not consistent with the parent block

2022-10-12 17:34 UTC, musayann commented on src/product.html
> +          <a class="button button--primary ml-5" href="">Free trial</a>
The class name is not consistent with the parent block

2022-10-12 17:34 UTC, musayann commented on src/product.html
> +    <section class="service" style="background-image: url(./img/Blur2.png)">
Move the style definition inside the css file

2022-10-12 17:34 UTC, musayann commented on src/product.html
> +            <a class="button button--light"> Subscribe </a>
The class name is not consistent with the parent block

2022-10-13 10:36 UTC, mbukeRepo approved these changes
well done you applied changes :+1:

2026-06-13 13:01 UTC, closed without merging